# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor_torch = torch.rand(7,7)
print(tensor_torch)

tensor([[0.6765, 0.4579, 0.3746, 0.1560, 0.7521, 0.2899, 0.8606],
        [0.5862, 0.9106, 0.8309, 0.0178, 0.8210, 0.5631, 0.1317],
        [0.6301, 0.4301, 0.1487, 0.7250, 0.0102, 0.2010, 0.8074],
        [0.9138, 0.9163, 0.9755, 0.3750, 0.3979, 0.0871, 0.0692],
        [0.3188, 0.8028, 0.2329, 0.5981, 0.3203, 0.9430, 0.0106],
        [0.0648, 0.1781, 0.8017, 0.4381, 0.2355, 0.4124, 0.4845],
        [0.2390, 0.3104, 0.3941, 0.5509, 0.1011, 0.6149, 0.5059]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
tensor_2 = torch.rand(1,7)
tensor_2_T = tensor_2.T
# Perform matrix multiplication
result = torch.matmul(tensor_torch, tensor_2_T)
print(result)

tensor([[1.0194],
        [1.6040],
        [0.7859],
        [1.6517],
        [1.1751],
        [0.8487],
        [0.8085]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [8]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7,7)
tensor2 = torch.rand(1,7)
tensor2_t = tensor2.T

# Matrix multiply tensors
result = torch.matmul(tensor1, tensor2_t)
print(result)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [34]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
  print('Device: cuda')
else:
  print('Device: cpu')

# Create two random tensors on GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
tensor_A = torch.rand(2,3, device=device)
tensor_B = torch.rand(2,3, device=device)
print(tensor_A)
print(tensor_B)

Device: cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [35]:
# Perform matmul on tensor_A and tensor_B
tensor_B = tensor_B.T
output_7 = torch.matmul(tensor_A, tensor_B)
print(output_7)

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [37]:
# Find max
print(torch.max(output_7))

# Find min
print(torch.min(output_7))

tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [42]:
# Find arg max
print(torch.argmax(output_7))

# Find arg min
print(torch.argmin(output_7))


tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [43]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor1 = torch.rand(1,1,1,10)

# Remove single dimensions
tensor2 = tensor1.squeeze()

# Print out tensors and their shapes
print(tensor1, tensor1.shape)
print(tensor2, tensor2.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
